name: iptv_checker_flutter
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  flutter_hls_parser: ^2.0.0
  dio: ^4.0.6
  flustars: ^2.0.1
  logger: ^1.1.0
  simple_animations: ^3.1.1
  m3u_nullsafe: ^1.0.4
  file_saver: ^0.1.1
  flutter:
    sdk: flutter

dev_dependencies: 
  flutter_lints: 2.0.1
  test: ^1.21.4
  flutter_test: 
    sdk: flutter

flutter:
  assets:
    - assets/
    - assets/categories.json
    - assets/countries.json
  uses-material-design: true

